[package]
name = "carbonyl"
version = "0.0.1"
edition = "2021"

[dependencies]
libc = "0.2"
unicode-width = "0.1.10"
unicode-segmentation = "1.10.0"

[lib]
name = "carbonyl"
path = "src/lib.rs"
crate-type = ["staticlib"]
